blank_issues_enabled: false
contact_links:
  - name: V2Ray Program Issues
    url: https://github.com/v2fly/v2ray-core/
    about: If you have questions about V2Ray instead of Boxfish, please go to this link to discuss.